wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 100
epoch:
  desc: null
  value: 300
experiment:
  desc: null
  value: 1202_ensemble_AT
gpu_device:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 3
test:
  desc: null
  value: 2
